# values.yaml
# -----------------------------------------------------------------------------
# Global
# -----------------------------------------------------------------------------
awsAccountID: "704505749045"
kafkaBootstrapServers: "my-kafka-cluster-kafka-bootstrap:9092" # <-- SET THIS


# -----------------------------------------------------------------------------
# StorageClass
# -----------------------------------------------------------------------------
storageClass:
  # Set to false if you are managing the StorageClass outside of Helm (e.g., with Terraform)
  # and it already exists in the cluster.
  create: true
  name: gp3
  provisioner: ebs.csi.aws.com
  volumeBindingMode: WaitForFirstConsumer
  parameters:
    type: gp3

# -----------------------------------------------------------------------------
# MySQL
# -----------------------------------------------------------------------------
mysql:
  image:
    repository: mysql
    tag: "8.0"
  
  # Credentials and Database Name
  # It's recommended to use --set for these or use a secret management system
  database: Payoneer
  rootPassword: "123456" # <-- Change this for production

  # PVC Configuration
  storage:
    size: 10Gi

  # init.sql script is now managed in templates/02-mysql-configmap.yml

# -----------------------------------------------------------------------------
# Producer Application
# -----------------------------------------------------------------------------
producer:
  image:
    repository: kafka-data-shipper
    tag: producer-latest
  
  # Spring Boot Actuator Port
  port: 8080

# -----------------------------------------------------------------------------
# Consumer Application
# -----------------------------------------------------------------------------
consumer:
  image:
    repository: kafka-data-shipper
    tag: consumer-latest
  
  # Spring Boot Actuator Port
  port: 8080

