# -----------------------------------------------------------------------------
# Global
# -----------------------------------------------------------------------------
awsAccountID: "704505749045"
kafkaBootstrapServers: "my-kafka-cluster-kafka-bootstrap:9092"


# -----------------------------------------------------------------------------
# StorageClass
# -----------------------------------------------------------------------------
storageClass:
  # Set to false if you are managing the StorageClass outside of Helm (e.g., with Terraform)
  create: true
  name: gp3
  provisioner: ebs.csi.aws.com
  volumeBindingMode: WaitForFirstConsumer
  parameters:
    type: gp3

# -----------------------------------------------------------------------------
# MySQL
# -----------------------------------------------------------------------------
mysql:
  image:
    repository: mysql
    tag: "8.0"
  
  # Credentials and Database Name
  database: Payoneer
  rootPassword: "123456"

  storage:
    size: 10Gi


# -----------------------------------------------------------------------------
# Producer Application
# -----------------------------------------------------------------------------
producer:
  image:
    repository: kafka-data-shipper
    tag: producer-latest
  
  port: 8080

# -----------------------------------------------------------------------------
# Consumer Application
# -----------------------------------------------------------------------------
consumer:
  image:
    repository: kafka-data-shipper
    tag: consumer-latest
  
  port: 8080

