version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - app-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Payoneer
    volumes:
      - ./common-files/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - app-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: 'PASTE_YOUR_GENERATED_UUID_HERE' #The setup-dev.sh script handles that placeholder with sed
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data

  producer:
    build: ./common-files/producer
    container_name: producer
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Payoneer
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  producer-waiter:
    image: alpine:latest
    container_name: producer-waiter
    networks:
      - app-network
    depends_on:
      producer:
        condition: service_started
    command: ["/bin/sh", "-c", "echo 'Producer started, waiting 30s before starting consumer...'; sleep 30"]

  consumer:
    build: ./common-files/consumer
    container_name: consumer
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
      producer-waiter:
        condition: service_completed_successfully
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Payoneer
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  kafka-data: